services:

  postgres:
    image: postgres:15
    container_name: linktic-postgres
    environment:
      POSTGRES_DB: linktic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - linktic-net

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: linktic-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - linktic-net

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: linktic-catalog
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - linktic-net

  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    container_name: linktic-stock
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      catalog-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - linktic-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: linktic-frontend
    ports:
      - "9000:80"
    depends_on:
      - catalog-service
      - stock-service
    networks:
      - linktic-net

volumes:
  postgres_data:

networks:
  linktic-net:
    driver: bridge
